// This file provides tests for the client.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package retrodiffusion

import (
	"encoding/json/jsontext"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"github.com/go-api-libs/api"
)

func newTestServer(t *testing.T, status int) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
	}))
	t.Cleanup(srv.Close)
	return srv
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

func TestClient_Error(t *testing.T) {
	t.Run("CreateInference", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetInferenceJob", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetInferenceRequest", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetBalance", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("ListAvailableStyles", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("CreateUserStyle", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusCreated)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusCreated)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("DeleteUserStyle", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("UpdateUserStyle", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("ListEditTools", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("RunEditTool", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("EstimateEditToolCost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("FixPixelArtStandard", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("FixPixelArtNeural", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetServiceStatus", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})
}
