// This file provides tests for the client.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package retrodiffusion

import (
	"bytes"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"io"
	"maps"
	"net/http"
	"net/http/httptest"
	"net/url"
	"slices"
	"testing"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
	"github.com/go-api-libs/api"
)

func newTestServer(t *testing.T, status int) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
	}))
	t.Cleanup(srv.Close)
	return srv
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

func TestClient_Error(t *testing.T) {
	t.Run("CreateInference", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateInference(t.Context(), InferenceRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetInferenceJob", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceJob(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetInferenceRequest", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetInferenceRequest(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetBalance", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalance(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("ListAvailableStyles", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListAvailableStyles(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("CreateUserStyle", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusCreated)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusCreated)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.CreateUserStyle(t.Context(), CreateStyleRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("DeleteUserStyle", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.DeleteUserStyle(t.Context(), ""); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("UpdateUserStyle", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.UpdateUserStyle(t.Context(), "", nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("ListEditTools", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListEditTools(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("RunEditTool", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.RunEditTool(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("EstimateEditToolCost", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateEditToolCost(t.Context(), "", EditToolRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("FixPixelArtStandard", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtStandard(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("FixPixelArtNeural", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.FixPixelArtNeural(t.Context(), PixelFixerRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetServiceStatus", func(t *testing.T) {
		t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetServiceStatus(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})
}

func replay(t *testing.T) http.RoundTripper {
	t.Helper()

	interactions, err := cassette.InteractionsReadFile("../../api/interactions.json")
	if err != nil {
		t.Fatal(err)
	}

	var idx int
	return roundTripFunc(func(req *http.Request) (*http.Response, error) {
		if idx >= len(interactions) {
			return nil, fmt.Errorf("unexpected request: %s %s", req.Method, req.URL)
		}

		ia := interactions[idx]

		r, err := cassette.NewRequest(req)
		if err != nil {
			return nil, err
		}

		if r.URL != ia.Request.URL {
			return nil, fmt.Errorf("interaction #%d: got URL %s, want %s", idx, r.URL, ia.Request.URL)
		}

		if r.Method != ia.Request.Method {
			return nil, fmt.Errorf("interaction #%d: got method %s, want %s", idx, r.Method, ia.Request.Method)
		}

		gotBody := jsontext.Value(r.Body)
		gotBody.Canonicalize()

		wantBody := jsontext.Value(ia.Request.Body)
		wantBody.Canonicalize()

		if !bytes.Equal(gotBody, wantBody) {
			return nil, fmt.Errorf("interaction #%d: got body %s, want %s", idx, string(gotBody), string(wantBody))
		}

		if ia.Request.Headers == nil {
			ia.Request.Headers = http.Header{}
		}

		ia.Request.Headers.Set("User-Agent", defaultUserAgent)

		if len(ia.Request.Body) == 0 {
			ia.Request.Headers.Del("Content-Type")
		}

		if !maps.EqualFunc(r.Headers, ia.Request.Headers, slices.Equal) {
			return nil, fmt.Errorf("interaction #%d: got headers %s, want %s", idx, r.Headers, ia.Request.Headers)
		}

		idx++
		return &http.Response{
			Status:     fmt.Sprintf("%d %s", ia.Response.StatusCode, http.StatusText(ia.Response.StatusCode)),
			StatusCode: ia.Response.StatusCode,
			Header:     ia.Response.Headers.Clone(),
			Body:       io.NopCloser(bytes.NewReader(ia.Response.Body)),
		}, nil
	})
}

func TestClient_Interactions(t *testing.T) {
	ctx := t.Context()
	t.Setenv("RETRO_DIFFUSION_API_KEY", "************************************************")

	c, err := NewClient(WithHTTPClient(&http.Client{Transport: replay(t)}))
	if err != nil {
		t.Fatal(err)
	}

	if _, err := c.ListAvailableStyles(ctx, &ListAvailableStylesParams{
		Model: "rd_pro",
	}); err != nil {
		t.Fatalf("ListAvailableStyles: %v", err)
	}

	if _, err := c.ListAvailableStyles(ctx, &ListAvailableStylesParams{}); err != nil {
		t.Fatalf("ListAvailableStyles: %v", err)
	}

	if _, err := c.CreateInference(ctx, InferenceRequest{
		Prompt:                  "security officer (a soldier). A 34-year-old male human. Lean and wiry, with a posture that suggests he's always expecting something to break. He wears the standard grey-blue security fatigues, kept meticulously clean despite the dust of the colony. A thin, jagged scar running through his left eyebrow. He has a habit of clicking his tongue when he's impatient.",
		PromptStyle:             PromptStyleRdProTopdown,
		Width:                   128,
		Height:                  128,
		NumImages:               1,
		RemoveBg:                true,
		TileX:                   false,
		TileY:                   false,
		ReturnSpritesheet:       false,
		BypassPromptExpansion:   false,
		IncludeDownloadableData: false,
		CheckCost:               true,
		Async:                   false,
		UploadOutputs:           false,
	}); err != nil {
		t.Fatalf("CreateInference: %v", err)
	}

	if _, err := c.CreateInference(ctx, InferenceRequest{
		Prompt:                  "security officer (a soldier). A 34-year-old male human. Lean and wiry, with a posture that suggests he's always expecting something to break. He wears the standard grey-blue security fatigues, kept meticulously clean despite the dust of the colony. A thin, jagged scar running through his left eyebrow. He has a habit of clicking his tongue when he's impatient.",
		PromptStyle:             PromptStyleGameAssetrdFlux,
		Width:                   64,
		Height:                  64,
		NumImages:               1,
		RemoveBg:                true,
		TileX:                   false,
		TileY:                   false,
		ReturnSpritesheet:       false,
		UpscaleOutputFactor:     new(1),
		BypassPromptExpansion:   true,
		IncludeDownloadableData: false,
		CheckCost:               false,
		Async:                   false,
		UploadOutputs:           false,
	}); err != nil {
		t.Fatalf("CreateInference: %v", err)
	}
}
