// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package retrodiffusion

import (
	"context"
	"encoding/json/v2"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Retro Diffusion API"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "api.retrodiffusion.ai",
	Path:   "/v1",
}

// Client is an HTTP client for the retrodiffusion API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	for _, opt := range opts {
		opt(c)
	}

	return c, nil
}

// Main generation endpoint. Set check_cost=true for free price estimate. Set async=true for long-running jobs (animations/batches). Use upload_outputs=true for signed URLs.
//
//	POST /inferences
func (c *Client) CreateInference(ctx context.Context, body InferenceRequest) (*InferenceResponse, error) {
	return CreateInference[InferenceResponse](ctx, c, body)
}

// Main generation endpoint. Set check_cost=true for free price estimate. Set async=true for long-running jobs (animations/batches). Use upload_outputs=true for signed URLs.
// You can define a custom result to unmarshal the response into.
//
//	POST /inferences
func CreateInference[R any](ctx context.Context, c *Client, body InferenceRequest) (*R, error) {
	u := c.baseURL.JoinPath("inferences")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Sync success or check_cost result
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusAccepted:
		// Async accepted
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusBadRequest:
		// Invalid input or insufficient balance
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out Error
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Missing/invalid X-RD-Token
		return nil, fmt.Errorf("CreateInference: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Body failed validation
		return nil, fmt.Errorf("CreateInference: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Rate limited
		return nil, fmt.Errorf("CreateInference: status %s", rsp.Status)
	case http.StatusInternalServerError:
		// Temporary failure (charges refunded)
		return nil, fmt.Errorf("CreateInference: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Poll async inference job
//
//	GET /inferences/tasks/{task_id}
func (c *Client) GetInferenceJob(ctx context.Context, taskID string) (*TaskStatus, error) {
	return GetInferenceJob[TaskStatus](ctx, c, taskID)
}

// Poll async inference job
// You can define a custom result to unmarshal the response into.
//
//	GET /inferences/tasks/{task_id}
func GetInferenceJob[R any](ctx context.Context, c *Client, taskID string) (*R, error) {
	u := c.baseURL.JoinPath("inferences", "tasks", taskID)
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Task status
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusNotFound:
		// Task not found or not owned
		return nil, fmt.Errorf("GetInferenceJob: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Returns status, settings, billing, and freshly signed output URLs. Any active personal key from owning account may retrieve after key rotation.
//
//	GET /inferences/requests/{request_id}
func (c *Client) GetInferenceRequest(ctx context.Context, requestID string) (*GetInferenceRequestOkJSONResponse, error) {
	return GetInferenceRequest[GetInferenceRequestOkJSONResponse](ctx, c, requestID)
}

// Returns status, settings, billing, and freshly signed output URLs. Any active personal key from owning account may retrieve after key rotation.
// You can define a custom result to unmarshal the response into.
//
//	GET /inferences/requests/{request_id}
func GetInferenceRequest[R any](ctx context.Context, c *Client, requestID string) (*R, error) {
	u := c.baseURL.JoinPath("inferences", "requests", requestID)
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Request details + signed URLs
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusNotFound:
		// Unknown, non-owned, or expired
		return nil, fmt.Errorf("GetInferenceRequest: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Get balance and credits
//
//	GET /inferences/credits
func (c *Client) GetBalance(ctx context.Context) (*CreditsResponse, error) {
	return GetBalance[CreditsResponse](ctx, c)
}

// Get balance and credits
// You can define a custom result to unmarshal the response into.
//
//	GET /inferences/credits
func GetBalance[R any](ctx context.Context, c *Client) (*R, error) {
	u := c.baseURL.JoinPath("inferences", "credits")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Current balance
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusForbidden:
		// Invalid token
		return nil, fmt.Errorf("GetBalance: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Live style catalog with limits
//
//	GET /styles/selector
func (c *Client) ListAvailableStyles(ctx context.Context, params *ListAvailableStylesParams) (*ListAvailableStylesOkJSONResponse, error) {
	return ListAvailableStyles[ListAvailableStylesOkJSONResponse](ctx, c, params)
}

// Live style catalog with limits
// You can define a custom result to unmarshal the response into.
//
//	GET /styles/selector
func ListAvailableStyles[R any](ctx context.Context, c *Client, params *ListAvailableStylesParams) (*R, error) {
	u := c.baseURL.JoinPath("styles", "selector")
	if params != nil {
		q := make(url.Values, 2)

		if params.Model != "" {
			q["model"] = []string{params.Model}
		}

		if params.Tab != "" {
			q["tab"] = []string{params.Tab}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Array of style descriptors
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Create custom user style (RD Pro reference template)
//
//	POST /styles
func (c *Client) CreateUserStyle(ctx context.Context, body CreateStyleRequest) (*StyleResponse, error) {
	return CreateUserStyle[StyleResponse](ctx, c, body)
}

// Create custom user style (RD Pro reference template)
// You can define a custom result to unmarshal the response into.
//
//	POST /styles
func CreateUserStyle[R any](ctx context.Context, c *Client, body CreateStyleRequest) (*R, error) {
	u := c.baseURL.JoinPath("styles")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusCreated:
		// Style created
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Delete user style
//
//	DELETE /styles/{style_id}
func (c *Client) DeleteUserStyle(ctx context.Context, styleID string) (*DeleteUserStyleOkJSONResponse, error) {
	return DeleteUserStyle[DeleteUserStyleOkJSONResponse](ctx, c, styleID)
}

// Delete user style
// You can define a custom result to unmarshal the response into.
//
//	DELETE /styles/{style_id}
func DeleteUserStyle[R any](ctx context.Context, c *Client, styleID string) (*R, error) {
	u := c.baseURL.JoinPath("styles", styleID)
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodDelete,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Deleted
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Update user style
//
//	PATCH /styles/{style_id}
func (c *Client) UpdateUserStyle(ctx context.Context, styleID string, body *CreateStyleRequest) (*StyleResponse, error) {
	return UpdateUserStyle[StyleResponse](ctx, c, styleID, body)
}

// Update user style
// You can define a custom result to unmarshal the response into.
//
//	PATCH /styles/{style_id}
func UpdateUserStyle[R any](ctx context.Context, c *Client, styleID string, body *CreateStyleRequest) (*R, error) {
	u := c.baseURL.JoinPath("styles", styleID)
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPatch,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Updated
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// List enabled canvas edit tools
//
//	GET /edit/tools
func (c *Client) ListEditTools(ctx context.Context) (*ListEditToolsOkJSONResponse, error) {
	return ListEditTools[ListEditToolsOkJSONResponse](ctx, c)
}

// List enabled canvas edit tools
// You can define a custom result to unmarshal the response into.
//
//	GET /edit/tools
func ListEditTools[R any](ctx context.Context, c *Client) (*R, error) {
	u := c.baseURL.JoinPath("edit", "tools")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Tool list with costs, limits, api_fields
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Tools: image_edit, inpainting, outpainting, seam_tiling, background_remover, color_style_transfer, color_reducer, palette_converter, k_centroid_downscale, pixel_correction, rotate. Free tools may require min balance $0.01.
//
//	POST /edit/tools/{tool_id}
func (c *Client) RunEditTool(ctx context.Context, toolID string, body EditToolRequest) (*EditToolResponse, error) {
	return RunEditTool[EditToolResponse](ctx, c, toolID, body)
}

// Tools: image_edit, inpainting, outpainting, seam_tiling, background_remover, color_style_transfer, color_reducer, palette_converter, k_centroid_downscale, pixel_correction, rotate. Free tools may require min balance $0.01.
// You can define a custom result to unmarshal the response into.
//
//	POST /edit/tools/{tool_id}
func RunEditTool[R any](ctx context.Context, c *Client, toolID string, body EditToolRequest) (*R, error) {
	u := c.baseURL.JoinPath("edit", "tools", toolID)
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Tool result
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusBadRequest:
		// Semantically invalid or insufficient balance
		return nil, fmt.Errorf("RunEditTool: status %s", rsp.Status)
	case http.StatusNotFound:
		// Unknown/disabled tool
		return nil, fmt.Errorf("RunEditTool: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Schema mismatch
		return nil, fmt.Errorf("RunEditTool: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Estimate edit tool cost (no run)
//
//	POST /edit/tools/{tool_id}/estimate
func (c *Client) EstimateEditToolCost(ctx context.Context, toolID string, body EditToolRequest) (*EditToolEstimate, error) {
	return EstimateEditToolCost[EditToolEstimate](ctx, c, toolID, body)
}

// Estimate edit tool cost (no run)
// You can define a custom result to unmarshal the response into.
//
//	POST /edit/tools/{tool_id}/estimate
func EstimateEditToolCost[R any](ctx context.Context, c *Client, toolID string, body EditToolRequest) (*R, error) {
	u := c.baseURL.JoinPath("edit", "tools", toolID, "estimate")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Cost estimate
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Native Rust grid detection. 16x16 to 16 megapixels. Rate limits: 120/min with purchase history, else 10/min. Shared with neural.
//
//	POST /pixel-fixer/standard
func (c *Client) FixPixelArtStandard(ctx context.Context, body PixelFixerRequest) (*PixelFixerResponse, error) {
	return FixPixelArtStandard[PixelFixerResponse](ctx, c, body)
}

// Native Rust grid detection. 16x16 to 16 megapixels. Rate limits: 120/min with purchase history, else 10/min. Shared with neural.
// You can define a custom result to unmarshal the response into.
//
//	POST /pixel-fixer/standard
func FixPixelArtStandard[R any](ctx context.Context, c *Client, body PixelFixerRequest) (*R, error) {
	u := c.baseURL.JoinPath("pixel-fixer", "standard")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Fixed image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusRequestEntityTooLarge:
		// Request or output too large
		return nil, fmt.Errorf("FixPixelArtStandard: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Invalid image
		return nil, fmt.Errorf("FixPixelArtStandard: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Rate limit exceeded
		return nil, fmt.Errorf("FixPixelArtStandard: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Accepts larger sources, bilinear-downscales above 1MP budget. Optional width/height target (capped 16MP).
//
//	POST /pixel-fixer/neural
func (c *Client) FixPixelArtNeural(ctx context.Context, body PixelFixerRequest) (*PixelFixerResponse, error) {
	return FixPixelArtNeural[PixelFixerResponse](ctx, c, body)
}

// Accepts larger sources, bilinear-downscales above 1MP budget. Optional width/height target (capped 16MP).
// You can define a custom result to unmarshal the response into.
//
//	POST /pixel-fixer/neural
func FixPixelArtNeural[R any](ctx context.Context, c *Client, body PixelFixerRequest) (*R, error) {
	u := c.baseURL.JoinPath("pixel-fixer", "neural")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Fixed image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusRequestEntityTooLarge:
		// Request or output too large
		return nil, fmt.Errorf("FixPixelArtNeural: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Invalid image
		return nil, fmt.Errorf("FixPixelArtNeural: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Rate limit exceeded
		return nil, fmt.Errorf("FixPixelArtNeural: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Service status (no auth)
//
//	GET /status
func (c *Client) GetServiceStatus(ctx context.Context) (*StatusResponse, error) {
	return GetServiceStatus[StatusResponse](ctx, c)
}

// Service status (no auth)
// You can define a custom result to unmarshal the response into.
//
//	GET /status
func GetServiceStatus[R any](ctx context.Context, c *Client) (*R, error) {
	u := c.baseURL.JoinPath("status")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Per-model status
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
