// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package retrodiffusion

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Retro Diffusion API"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "api.retrodiffusion.ai",
	Path:   "/v1",
}

// Client is an HTTP client for the retrodiffusion API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The API key
	apiKey string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
	// Enable debug mode
	debug bool
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithAPIKey returns a [ClientOption] that sets a custom API key.
func WithAPIKey(apiKey string) ClientOption {
	return func(c *Client) { c.apiKey = apiKey }
}

// WithDebug is a [ClientOption] that sets the debug mode to true.
func WithDebug(c *Client) { c.debug = true }

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	c.apiKey = os.Getenv("RETRO_DIFFUSION_API_KEY")

	for _, opt := range opts {
		opt(c)
	}

	if c.apiKey == "" {
		return nil, errors.New("api key RETRO_DIFFUSION_API_KEY not provided")
	}

	return c, nil
}

// Main generation endpoint. Set check_cost=true for free price estimate. Set async=true for long-running jobs (animations/batches). Use upload_outputs=true for signed URLs.
//
//	POST /inferences
func (c *Client) CreateInference(ctx context.Context, body InferenceRequest) (*Inference, error) {
	return c.CreateInferenceWithResult[Inference](ctx, body)
}

// Main generation endpoint. Set check_cost=true for free price estimate. Set async=true for long-running jobs (animations/batches). Use upload_outputs=true for signed URLs.
// You can define a custom result to unmarshal the response into.
//
//	POST /inferences
func (c *Client) CreateInferenceWithResult[R any](ctx context.Context, body InferenceRequest) (*R, error) {
	u := c.baseURL.JoinPath("inferences")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token":   []string{c.apiKey},
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Sync success or check_cost result
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusAccepted:
		// Async accepted
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusBadRequest:
		// Invalid input or insufficient balance
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out APIError
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Missing/invalid X-RD-Token
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out APIError
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnprocessableEntity:
		// Body failed validation
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out APIError
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusTooManyRequests:
		// Rate limited
		return nil, fmt.Errorf("CreateInference: status %s", rsp.Status)
	case http.StatusInternalServerError:
		// Temporary failure (charges refunded)
		return nil, fmt.Errorf("CreateInference: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Poll async inference job
//
//	GET /inferences/tasks/{task_id}
func (c *Client) GetInferenceJob(ctx context.Context, taskID string) (*TaskStatus, error) {
	return c.GetInferenceJobWithResult[TaskStatus](ctx, taskID)
}

// Poll async inference job
// You can define a custom result to unmarshal the response into.
//
//	GET /inferences/tasks/{task_id}
func (c *Client) GetInferenceJobWithResult[R any](ctx context.Context, taskID string) (*R, error) {
	u := c.baseURL.JoinPath("inferences", "tasks", taskID)
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Task status
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusNotFound:
		// Task not found or not owned
		return nil, fmt.Errorf("GetInferenceJob: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Returns status, settings, billing, and freshly signed output URLs. Any active personal key from owning account may retrieve after key rotation.
//
//	GET /inferences/requests/{request_id}
func (c *Client) GetInferenceRequest(ctx context.Context, requestID string) (*InferenceRequestResult, error) {
	return c.GetInferenceRequestWithResult[InferenceRequestResult](ctx, requestID)
}

// Returns status, settings, billing, and freshly signed output URLs. Any active personal key from owning account may retrieve after key rotation.
// You can define a custom result to unmarshal the response into.
//
//	GET /inferences/requests/{request_id}
func (c *Client) GetInferenceRequestWithResult[R any](ctx context.Context, requestID string) (*R, error) {
	u := c.baseURL.JoinPath("inferences", "requests", requestID)
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Request details + signed URLs
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusNotFound:
		// Unknown, non-owned, or expired
		return nil, fmt.Errorf("GetInferenceRequest: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Get balance and credits
//
//	GET /inferences/credits
func (c *Client) GetBalance(ctx context.Context) (*CreditsResponse, error) {
	return c.GetBalanceWithResult[CreditsResponse](ctx)
}

// Get balance and credits
// You can define a custom result to unmarshal the response into.
//
//	GET /inferences/credits
func (c *Client) GetBalanceWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("inferences", "credits")
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Current balance
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusForbidden:
		// Invalid token
		return nil, fmt.Errorf("GetBalance: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Live style catalog with limits
//
//	GET /styles/selector
func (c *Client) ListAvailableStyles(ctx context.Context, params *ListAvailableStylesParams) (*StyleDescriptors, error) {
	return c.ListAvailableStylesWithResult[StyleDescriptors](ctx, params)
}

// Live style catalog with limits
// You can define a custom result to unmarshal the response into.
//
//	GET /styles/selector
func (c *Client) ListAvailableStylesWithResult[R any](ctx context.Context, params *ListAvailableStylesParams) (*R, error) {
	u := c.baseURL.JoinPath("styles", "selector")
	if params != nil {
		q := make(url.Values, 2)

		if params.Model != "" {
			q["model"] = []string{params.Model}
		}

		if params.Tab != "" {
			q["tab"] = []string{params.Tab}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Array of style descriptors
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Missing/invalid X-RD-Token
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out APIError
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Create custom user style (RD Pro reference template)
//
//	POST /styles
func (c *Client) CreateUserStyle(ctx context.Context, body CreateStyleRequest) (*Style, error) {
	return c.CreateUserStyleWithResult[Style](ctx, body)
}

// Create custom user style (RD Pro reference template)
// You can define a custom result to unmarshal the response into.
//
//	POST /styles
func (c *Client) CreateUserStyleWithResult[R any](ctx context.Context, body CreateStyleRequest) (*R, error) {
	u := c.baseURL.JoinPath("styles")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token":   []string{c.apiKey},
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusCreated:
		// Style created
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Delete user style
//
//	DELETE /styles/{style_id}
func (c *Client) DeleteUserStyle(ctx context.Context, styleID string) (*DeleteUserStyleOkJSONResponse, error) {
	return c.DeleteUserStyleWithResult[DeleteUserStyleOkJSONResponse](ctx, styleID)
}

// Delete user style
// You can define a custom result to unmarshal the response into.
//
//	DELETE /styles/{style_id}
func (c *Client) DeleteUserStyleWithResult[R any](ctx context.Context, styleID string) (*R, error) {
	u := c.baseURL.JoinPath("styles", styleID)
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodDelete,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Deleted
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Update user style
//
//	PATCH /styles/{style_id}
func (c *Client) UpdateUserStyle(ctx context.Context, styleID string, body *CreateStyleRequest) (*Style, error) {
	return c.UpdateUserStyleWithResult[Style](ctx, styleID, body)
}

// Update user style
// You can define a custom result to unmarshal the response into.
//
//	PATCH /styles/{style_id}
func (c *Client) UpdateUserStyleWithResult[R any](ctx context.Context, styleID string, body *CreateStyleRequest) (*R, error) {
	u := c.baseURL.JoinPath("styles", styleID)
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token":   []string{c.apiKey},
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPatch,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Updated
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// List enabled canvas edit tools
//
//	GET /edit/tools
func (c *Client) ListEditTools(ctx context.Context) (*ListEditToolsOkJSONResponse, error) {
	return c.ListEditToolsWithResult[ListEditToolsOkJSONResponse](ctx)
}

// List enabled canvas edit tools
// You can define a custom result to unmarshal the response into.
//
//	GET /edit/tools
func (c *Client) ListEditToolsWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("edit", "tools")
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Tool list with costs, limits, api_fields
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Tools: image_edit, inpainting, outpainting, seam_tiling, background_remover, color_style_transfer, color_reducer, palette_converter, k_centroid_downscale, pixel_correction, rotate. Free tools may require min balance $0.01.
//
//	POST /edit/tools/{tool_id}
func (c *Client) RunEditTool(ctx context.Context, toolID string, body EditToolRequest) (*EditToolResponse, error) {
	return c.RunEditToolWithResult[EditToolResponse](ctx, toolID, body)
}

// Tools: image_edit, inpainting, outpainting, seam_tiling, background_remover, color_style_transfer, color_reducer, palette_converter, k_centroid_downscale, pixel_correction, rotate. Free tools may require min balance $0.01.
// You can define a custom result to unmarshal the response into.
//
//	POST /edit/tools/{tool_id}
func (c *Client) RunEditToolWithResult[R any](ctx context.Context, toolID string, body EditToolRequest) (*R, error) {
	u := c.baseURL.JoinPath("edit", "tools", toolID)
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token":   []string{c.apiKey},
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Tool result
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusBadRequest:
		// Semantically invalid or insufficient balance
		return nil, fmt.Errorf("RunEditTool: status %s", rsp.Status)
	case http.StatusNotFound:
		// Unknown/disabled tool
		return nil, fmt.Errorf("RunEditTool: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Schema mismatch
		return nil, fmt.Errorf("RunEditTool: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Estimate edit tool cost (no run)
//
//	POST /edit/tools/{tool_id}/estimate
func (c *Client) EstimateEditToolCost(ctx context.Context, toolID string, body EditToolRequest) (*EditToolEstimate, error) {
	return c.EstimateEditToolCostWithResult[EditToolEstimate](ctx, toolID, body)
}

// Estimate edit tool cost (no run)
// You can define a custom result to unmarshal the response into.
//
//	POST /edit/tools/{tool_id}/estimate
func (c *Client) EstimateEditToolCostWithResult[R any](ctx context.Context, toolID string, body EditToolRequest) (*R, error) {
	u := c.baseURL.JoinPath("edit", "tools", toolID, "estimate")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token":   []string{c.apiKey},
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Cost estimate
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Native Rust grid detection. 16x16 to 16 megapixels. Rate limits: 120/min with purchase history, else 10/min. Shared with neural.
//
//	POST /pixel-fixer/standard
func (c *Client) FixPixelArtStandard(ctx context.Context, body PixelFixerRequest) (*PixelFixerResponse, error) {
	return c.FixPixelArtStandardWithResult[PixelFixerResponse](ctx, body)
}

// Native Rust grid detection. 16x16 to 16 megapixels. Rate limits: 120/min with purchase history, else 10/min. Shared with neural.
// You can define a custom result to unmarshal the response into.
//
//	POST /pixel-fixer/standard
func (c *Client) FixPixelArtStandardWithResult[R any](ctx context.Context, body PixelFixerRequest) (*R, error) {
	u := c.baseURL.JoinPath("pixel-fixer", "standard")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token":   []string{c.apiKey},
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Fixed image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusRequestEntityTooLarge:
		// Request or output too large
		return nil, fmt.Errorf("FixPixelArtStandard: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Invalid image
		return nil, fmt.Errorf("FixPixelArtStandard: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Rate limit exceeded
		return nil, fmt.Errorf("FixPixelArtStandard: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Accepts larger sources, bilinear-downscales above 1MP budget. Optional width/height target (capped 16MP).
//
//	POST /pixel-fixer/neural
func (c *Client) FixPixelArtNeural(ctx context.Context, body PixelFixerRequest) (*PixelFixerResponse, error) {
	return c.FixPixelArtNeuralWithResult[PixelFixerResponse](ctx, body)
}

// Accepts larger sources, bilinear-downscales above 1MP budget. Optional width/height target (capped 16MP).
// You can define a custom result to unmarshal the response into.
//
//	POST /pixel-fixer/neural
func (c *Client) FixPixelArtNeuralWithResult[R any](ctx context.Context, body PixelFixerRequest) (*R, error) {
	u := c.baseURL.JoinPath("pixel-fixer", "neural")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token":   []string{c.apiKey},
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Fixed image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusRequestEntityTooLarge:
		// Request or output too large
		return nil, fmt.Errorf("FixPixelArtNeural: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Invalid image
		return nil, fmt.Errorf("FixPixelArtNeural: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Rate limit exceeded
		return nil, fmt.Errorf("FixPixelArtNeural: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Service status (no auth)
//
//	GET /status
func (c *Client) GetServiceStatus(ctx context.Context) (*StatusResponse, error) {
	return c.GetServiceStatusWithResult[StatusResponse](ctx)
}

// Service status (no auth)
// You can define a custom result to unmarshal the response into.
//
//	GET /status
func (c *Client) GetServiceStatusWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("status")
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// Per-model status
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if c.debug {
					if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
						return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
					}
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
