// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package retrodiffusion

import (
	"encoding/json/v2"
	"net/url"

	"github.com/MarkRosemaker/jsonutil"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.URLMarshal),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.URLUnmarshal),
	)),
)

// ListAvailableStylesParams holds the query parameters for ListAvailableStyles.
type ListAvailableStylesParams struct {
	Model string
	Tab   string
}

// AsyncAccepted defines a model
type AsyncAccepted struct {
	Status    string `json:"status,omitzero"`
	TaskID    string `json:"task_id,omitzero"`
	RequestID string `json:"request_id,omitzero"`
	Message   string `json:"message,omitzero"`
}

// CreateStyleRequest defines a model
type CreateStyleRequest struct {
	Name             string   `json:"name,omitzero"`
	Description      string   `json:"description,omitzero"`
	StyleIcon        string   `json:"style_icon,omitzero"`
	ReferenceImages  []string `json:"reference_images,omitempty"`
	ReferenceCaption string   `json:"reference_caption,omitzero"`
	ApplyPromptFixer bool     `json:"apply_prompt_fixer,omitempty"`
	LlmInstructions  string   `json:"llm_instructions,omitzero"`
	// Must contain the token {prompt}
	UserPromptTemplate string `json:"user_prompt_template,omitzero"`
	ForcePalette       bool   `json:"force_palette,omitempty"`
	ForceBgRemoval     bool   `json:"force_bg_removal,omitempty"`
	MinWidth           *int   `json:"min_width,omitempty"`
	MinHeight          *int   `json:"min_height,omitempty"`
}

// CreditsResponse defines a model
type CreditsResponse struct {
	Credits *float64 `json:"credits,omitempty"`
	Balance *float64 `json:"balance,omitempty"`
}

// DeleteUserStyleOkJSONResponse defines a model
type DeleteUserStyleOkJSONResponse struct {
	Deleted bool `json:"deleted,omitempty"`
}

// EditToolEstimate defines a model
type EditToolEstimate struct {
	ToolID          string   `json:"tool_id,omitzero"`
	BalanceCost     *float64 `json:"balance_cost,omitempty"`
	CreditCost      *float64 `json:"credit_cost,omitempty"`
	EstimateSeconds *float64 `json:"estimate_seconds,omitempty"`
}

// EditToolRequest defines a model
type EditToolRequest struct {
	// Raw base64 or data:image/...;base64 data URI
	InputImage string `json:"input_image,omitzero"`
	// For correlating runs with your queue (not idempotency key)
	CustomID string `json:"custom_id,omitzero"`
	Prompt   string `json:"prompt,omitzero"`
	Seed     *int   `json:"seed,omitempty"`
	// For inpainting. RGBA PNG preferred: alpha 0 protects, alpha >12 selects. Grayscale also accepted.
	MaskImage             string                    `json:"mask_image,omitzero"`
	SoftInpaint           bool                      `json:"soft_inpaint,omitempty"`
	ExpandLeft            *int                      `json:"expand_left,omitempty"`
	ExpandRight           *int                      `json:"expand_right,omitempty"`
	ExpandTop             *int                      `json:"expand_top,omitempty"`
	ExpandBottom          *int                      `json:"expand_bottom,omitempty"`
	TileX                 bool                      `json:"tile_x,omitempty"`
	TileY                 bool                      `json:"tile_y,omitempty"`
	SeamWidth             *int                      `json:"seam_width,omitempty"`
	RepairWindowSize      *int                      `json:"repair_window_size,omitempty"`
	TransparencyThreshold *float64                  `json:"transparency_threshold,omitempty"`
	ForceSolidPixels      bool                      `json:"force_solid_pixels,omitempty"`
	ExtraInputImage       string                    `json:"extra_input_image,omitzero"`
	ColorCount            *int                      `json:"color_count,omitempty"`
	DitherMode            EditToolRequestDitherMode `json:"dither_mode,omitzero"`
	DitherStrength        *int                      `json:"dither_strength,omitempty"`
	InputPalette          string                    `json:"input_palette,omitzero"`
	Width                 *int                      `json:"width,omitempty"`
	Height                *int                      `json:"height,omitempty"`
	RotationDegrees       *int                      `json:"rotation_degrees,omitempty"`
}

// EditToolRequestDitherMode defines a model
type EditToolRequestDitherMode string

const (
	EditToolRequestDitherModeNone     EditToolRequestDitherMode = "none"
	EditToolRequestDitherModeBayer2x2 EditToolRequestDitherMode = "bayer_2x2"
	EditToolRequestDitherModeBayer4x4 EditToolRequestDitherMode = "bayer_4x4"
	EditToolRequestDitherModeBayer8x8 EditToolRequestDitherMode = "bayer_8x8"
)

// Valid indicates whether the value is a known member of the EditToolRequestDitherMode enum.
func (e EditToolRequestDitherMode) Valid() bool {
	switch e {
	case EditToolRequestDitherModeNone, EditToolRequestDitherModeBayer2x2, EditToolRequestDitherModeBayer4x4, EditToolRequestDitherModeBayer8x8:
		return true
	default:
		return false
	}
}

// EditToolResponse defines a model
type EditToolResponse struct {
	ToolID           string   `json:"tool_id,omitzero"`
	InferenceID      string   `json:"inference_id,omitzero"`
	Base64Images     []string `json:"base64_images,omitempty"`
	OutputUrls       []string `json:"output_urls,omitempty"`
	BalanceCost      *float64 `json:"balance_cost,omitempty"`
	CreditCost       *float64 `json:"credit_cost,omitempty"`
	Charged          bool     `json:"charged,omitempty"`
	RemainingBalance *float64 `json:"remaining_balance,omitempty"`
}

// NOTE: could also be "Errors"
type Error struct {
	Detail ErrorCodeAndMessage `json:"detail"`
}

// ErrorCodeAndMessage defines a model
type ErrorCodeAndMessage struct {
	Code    string `json:"code,omitzero"`
	Message string `json:"message,omitzero"`
}

// ErrorDetail defines a model
type ErrorDetail struct {
	Msg string `json:"msg,omitzero"`
}

// ErrorDetails defines a model
type ErrorDetails []ErrorDetail

// Errors defines a model
type Errors struct {
	Detail ErrorDetails `json:"detail,omitempty"`
}

// GetInferenceRequestOkJSONResponse defines a model
type GetInferenceRequestOkJSONResponse map[string]struct{}

// InferenceRequest defines a model
type InferenceRequest struct {
	// Describe the SUBJECT only. Never write 'pixel art'.
	Prompt string `json:"prompt,omitzero"`
	// Style id e.g. rd_fast__default, rd_pro__default, rd_plus__default, animation/tile variants, or user__name_id
	PromptStyle string `json:"prompt_style,omitzero"`
	// Style-enforced tighter limits apply (most top out at 384)
	Width     int `json:"width,omitzero"`
	Height    int `json:"height,omitzero"`
	NumImages int `json:"num_images,omitzero"`
	// Reproducible generation
	Seed *int `json:"seed,omitempty"`
	// Raw base64 PNG (no data: URI prefix), RGB no transparency. Required for img2img, advanced animation, some edit tools.
	InputImage string `json:"input_image,omitzero"`
	// How much to change input_image
	Strength *float64 `json:"strength,omitempty"`
	// Base64 images. RD Pro styles only. Guides style/content.
	ReferenceImages []string `json:"reference_images,omitempty"`
	// Base64 palette constraining output colors
	InputPalette string `json:"input_palette,omitzero"`
	// Transparent output
	RemoveBg bool `json:"remove_bg,omitempty"`
	TileX    bool `json:"tile_x,omitempty"`
	TileY    bool `json:"tile_y,omitempty"`
	// Animation styles only
	FramesDuration *int `json:"frames_duration,omitempty"`
	// Animations: PNG spritesheet instead of GIF
	ReturnSpritesheet bool `json:"return_spritesheet,omitempty"`
	// 1 = native pixel size
	UpscaleOutputFactor *int `json:"upscale_output_factor,omitempty"`
	// Skip automatic LLM prompt enrichment
	BypassPromptExpansion bool `json:"bypass_prompt_expansion,omitempty"`
	// Extra structured assets e.g. item atlas JSON
	IncludeDownloadableData bool `json:"include_downloadable_data,omitempty"`
	// FREE dry run: returns price, generates nothing, charges nothing
	CheckCost bool `json:"check_cost,omitempty"`
	// Return task_id for polling instead of waiting
	Async bool `json:"async,omitempty"`
	// Receive temporary signed URLs in output_urls instead of (or with) base64
	UploadOutputs bool `json:"upload_outputs,omitempty"`
	// For advanced tileset styles
	ExtraPrompt string `json:"extra_prompt,omitzero"`
	// For advanced tileset styles
	ExtraInputImage string `json:"extra_input_image,omitzero"`
	// Placeholder — current models ignore it. Do not rely on it.
	Negative string `json:"negative,omitzero"`
}

// InferenceResponse defines a model
type InferenceResponse struct {
	CreatedAt   *int     `json:"created_at,omitempty"`
	BalanceCost *float64 `json:"balance_cost,omitempty"`
	// Raw base64 PNG (or GIF for animations)
	Base64Images []string `json:"base64_images,omitempty"`
	// 15-minute signed URLs when upload_outputs=true
	OutputUrls           []string `json:"output_urls,omitempty"`
	Model                string   `json:"model,omitzero"`
	RemainingBalance     *float64 `json:"remaining_balance,omitempty"`
	RequestID            string   `json:"request_id,omitzero"`
	OutputsRetainedUntil *int     `json:"outputs_retained_until,omitempty"`
}

// ListAvailableStylesOkJSONResponse defines a model
type ListAvailableStylesOkJSONResponse []StyleSelectorItem

// ListEditToolsOkJSONResponse defines a model
type ListEditToolsOkJSONResponse []map[string]struct{}

// Provide exactly one of input_image or image_url. width/height are optional and only used by the neural endpoint.
type PixelFixerRequest struct {
	// Raw base64 PNG/JPEG/WebP or data URI
	InputImage string `json:"input_image,omitzero"`
	// Public HTTPS PNG/JPEG/WebP
	ImageURL *url.URL `json:"image_url,omitempty"`
	// Neural only: target output width
	Width *int `json:"width,omitempty"`
	// Neural only: target output height
	Height *int `json:"height,omitempty"`
}

// PixelFixerResponse defines a model
type PixelFixerResponse struct {
	Base64Images [1]string `json:"base64_images,omitempty"`
}

// StatusResponse defines a model
type StatusResponse struct {
	Status    *map[string]string `json:"status,omitempty"`
	UpdatedAt *int               `json:"updated_at,omitempty"`
}

// StyleResponse defines a model
type StyleResponse struct {
	ID          string `json:"id,omitzero"`
	PromptStyle string `json:"prompt_style,omitzero"`
	Name        string `json:"name,omitzero"`
	Type        string `json:"type,omitzero"`
}

// StyleSelectorItem defines a model
type StyleSelectorItem struct {
	PromptStyle             string `json:"prompt_style,omitzero"`
	Name                    string `json:"name,omitzero"`
	Description             string `json:"description,omitzero"`
	RequiredModel           string `json:"required_model,omitzero"`
	RequiredTab             string `json:"required_tab,omitzero"`
	MinWidth                *int   `json:"min_width,omitempty"`
	MaxWidth                *int   `json:"max_width,omitempty"`
	MinHeight               *int   `json:"min_height,omitempty"`
	MaxHeight               *int   `json:"max_height,omitempty"`
	MaxNumberOfImages       *int   `json:"max_number_of_images,omitempty"`
	RequireInputImage       bool   `json:"require_input_image,omitempty"`
	SupportsReferenceImages bool   `json:"supports_reference_images,omitempty"`
	ExamplePrompt           string `json:"example_prompt,omitzero"`
}

// TaskStatus defines a model
type TaskStatus struct {
	Status TaskStatusStatus   `json:"status,omitzero"`
	TaskID string             `json:"task_id,omitzero"`
	Result *InferenceResponse `json:"result,omitempty"`
	Err    *TaskStatusError   `json:"error,omitempty"`
}

// TaskStatusError defines a model
type TaskStatusError struct {
	StatusCode *int   `json:"status_code,omitempty"`
	Detail     string `json:"detail,omitzero"`
}

// TaskStatusStatus defines a model
type TaskStatusStatus string

const (
	TaskStatusStatusPending   TaskStatusStatus = "pending"
	TaskStatusStatusRunning   TaskStatusStatus = "running"
	TaskStatusStatusSucceeded TaskStatusStatus = "succeeded"
	TaskStatusStatusFailed    TaskStatusStatus = "failed"
)

// Valid indicates whether the value is a known member of the TaskStatusStatus enum.
func (e TaskStatusStatus) Valid() bool {
	switch e {
	case TaskStatusStatusPending, TaskStatusStatusRunning, TaskStatusStatusSucceeded, TaskStatusStatusFailed:
		return true
	default:
		return false
	}
}
